# Generated by Django 5.0 on 2024-01-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/collections')),
                ('name', models.CharField(default='some titled picture', max_length=30)),
                ('category', models.CharField(default='Image', max_length=20)),
                ('items_in_collection', models.CharField(default='1/1', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/market')),
                ('name', models.CharField(default='some titled picture', max_length=30)),
                ('author_name', models.CharField(default='Owner', max_length=20)),
                ('author_link', models.CharField(default='@author_link', max_length=40)),
                ('ends_in', models.DateTimeField()),
                ('current_bid', models.CharField(max_length=25)),
                ('current_price', models.CharField(max_length=25)),
            ],
        ),
    ]
